#!/bin/sh

xidfile="$HOME/.surf/tabbed-surf.xid"
uri=""

if [ "$#" -gt 0 ] ; then
	uri="$1"
fi

runclean() {
	tabbed -dn tabbed-surf -r 2 surf -e '' "$uri" >"$xidfile" \
		2>/dev/null &
}

dumpsession() {
    
}

if [ ! -r "$xidfile" ] ; then
	runclean
else
	xid=$(cat "$xidfile")
	xprop -id "$xid" >/dev/null 2>&1
	if [ $? -gt 0 ] ; then
		runclean
	else
		surf -e "$xid" "$uri" >/dev/null 2>&1 &
	fi
fi

pidof "$0" >/dev/null
while [ "$?" -ne 0 ] ; do
    sleep 2
    pidof "$0" >/dev/null
done

dumpsession

exit 0
